kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm
      name: tiller
  template:
    metadata:
      labels:
        app: helm
        name: tiller
    spec:
      containers:
      - image: gcr.io/kubernetes-helm/tiller:v2.0.0-alpha.5
        env:
          - name: KUBECONFIG
            value: /etc/kubernetes/tiller.kubeconfig
        livenessProbe:
          httpGet:
            path: /liveness
            port: 44135
            scheme: HTTP
        name: tiller
        volumeMounts:
          - name: ca-crt
            mountPath: /etc/kubernetes/certs/ca.crt
            readOnly: true
          - name: tiller-kubeconfig
            mountPath: /etc/kubernetes/tiller.kubeconfig
            readOnly: true
        ports:
        - containerPort: 44134
          name: tiller
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readiness
            port: 44135
            scheme: HTTP
      nodeSelector:
        node: master
      volumes:
        - name: ca-crt
          hostPath:
            path: /etc/kubernetes/certs/ca.crt
        - name: tiller-kubeconfig
          hostPath:
            path: /etc/kubernetes/tiller.kubeconfig
