---

  - name: All K8 nodes
    hosts: all
    user: root
    become: yes
    roles:
      - common
      - flannel
      - docker
    tags:
      - all

  - name: K8 master
    hosts: master
    user: root
    become: yes
    roles:
      - etcd
      - kubernetes
      - k8-master
    tags:
      - master

  - name: K8 node
    hosts: nodes
    user: root
    become: yes
    roles:
      - kubernetes
      - k8-node
    tags:
      - node
