---

  - name: K8 all nodes
    hosts: all-k8s
    user: root
    roles:
      - common
      - kubernetes
    tags:
      - all-nodes

  - name: K8S prepare master
    hosts: master
    user: root
    roles:
      - etcd
      - flannel
      - docker
    tags:
      - master
      - master-prep

  - name: K8S install master
    hosts: master
    user: root
    roles:
      - k8s-master
    tags:
      - master
      - master-install

  - name: K8S install master addons
    hosts: master
    user: root
    roles:
      - k8s-dns
      - k8s-dashboard
    tags:
      - master
      - master-addons

  - name: K8S nodes
    hosts: nodes
    user: root
    roles:
      - flannel
      - docker
      - k8s-node
    tags:
      - nodes

  - name: K8S nodes
    hosts: nodes
    user: root
    roles:
      - glusterfs
    tags:
      - glusterfs
