---

  - name: Move kube-proxy binarys to sys path.
    command: cp -v /root/kubernetes/server/bin/kube-proxy /usr/bin/kube-proxy creates=/usr/bin/kube-proxy

  - name: Create /etc/kubernetes dir
    file:
      path: /etc/kubernetes/manifests
      state: directory

  - name: Add kube-proxy conf.
    copy:
      src: proxy
      dest: /etc/kubernetes/proxy
      mode: 0644
    notify:
      - restart kube-proxy

  - name: Clone github repo kubernetes/contrib
    git:
      repo: https://github.com/kubernetes/contrib.git
      dest: /root/contrib

  - name: Copy kube-proxy.service file
    command: cp -v /root/contrib/init/systemd/kube-proxy.service /usr/lib/systemd/system/kube-proxy.service creates=/usr/lib/systemd/system/kube-proxy.service

  - name: Enable/Start kube-proxy service
    service:
      name: kube-proxy
      enabled: yes
      state: started
